# Generated by Django 4.2.3 on 2023-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, verbose_name='نام ورزشکار')),
                ('seri1', models.IntegerField(default=None, max_length=200, verbose_name='سری اول')),
                ('seri2', models.IntegerField(default=None, max_length=200, verbose_name='سری دوم')),
                ('num11', models.IntegerField(default=None, max_length=200, verbose_name='شماره 11')),
                ('num12', models.IntegerField(default=None, max_length=200, verbose_name='شماره 12')),
                ('num13', models.IntegerField(default=None, max_length=200, verbose_name='شماره 13')),
                ('num14', models.IntegerField(default=None, max_length=200, verbose_name='شماره 14')),
                ('num15', models.IntegerField(default=None, max_length=200, verbose_name='شماره 15')),
                ('num16', models.IntegerField(default=None, max_length=200, verbose_name='شماره 16')),
                ('num17', models.IntegerField(default=None, max_length=200, verbose_name='شماره 17')),
                ('num18', models.IntegerField(default=None, max_length=200, verbose_name='شماره 18')),
                ('num19', models.IntegerField(default=None, max_length=200, verbose_name='شماره 19')),
                ('num20', models.IntegerField(default=None, max_length=200, verbose_name='شماره 20')),
                ('num21', models.IntegerField(default=None, max_length=200, verbose_name='شماره 21')),
                ('num22', models.IntegerField(default=None, max_length=200, verbose_name='شماره 22')),
                ('num23', models.IntegerField(default=None, max_length=200, verbose_name='شماره 23')),
                ('num24', models.IntegerField(default=None, max_length=200, verbose_name='شماره 24')),
                ('total', models.IntegerField(default=None, max_length=200, verbose_name='مجموع')),
            ],
        ),
    ]
