# Generated by Django 4.2.3 on 2023-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_final_user_num11_alter_final_user_num12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_user',
            name='num11',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 11'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num12',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 12'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num13',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 13'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num14',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 14'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num15',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 15'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num16',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 16'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num17',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 17'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num18',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 18'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num19',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 19'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num20',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 20'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num21',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 21'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num22',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 22'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num23',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 23'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='num24',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره 24'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='seri1',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='سری اول'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='seri2',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='سری دوم'),
        ),
        migrations.AlterField(
            model_name='final_user',
            name='total',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='مجموع'),
        ),
    ]
